baseurl: "/"
title: "GOCON CANADA"
canonifyurls: true
theme: "goconca"
dataDir: "Dat"

GoogleAnalytics: "UA-127047731-1"

params:
  # Conference info
  Name: "GOCON CANADA"
  Description: "Canadian Go Conference"
  Date: "May 31, 2019"
  # Price: "UNKNOWN" # If your event is free, just comment this line
  Venue: "St. James Cathedral Centre"
  Address: "65 Church Street"
  City:  "Toronto"
  State: "Ontario"
  Postcode: "M5C 2E9"
  Images: ["/img/toronto.jpg"]
  GoogleMapsKey: "AIzaSyD75cSNgqEfqbKAq-2aeBJV0gjYBw4Ys88"
  Twitter: goconcanada

  Cfp:
    Title: "Submit your talk proposal now!"
    Url: https://www.papercall.io/goconca

  Organizers:
    - name: Mike Fridman
      homepage: https://mfridman.com
      twitter:
    - name: Zach Goldstein
      homepage: https://zachgoldstein.github.io/
      twitter:
    - name: Lubov Soltan
      homepage: https://lubovsoltan.wixsite.com/lubovsoltan
      twitter:
    - name: Max Gonzih
      homepage: https://gonzih.me/
      twitter:
    - name: Dylan Arbour
      homepage: https://dylanarbour.com/
      twitter:

  Nav:
    - Url: "/#about"
      Title: "About"
    - Url: "/#schedule"
      Title: "Schedule"
    - Url: "/#sponsors"
      Title: "Sponsors"
    - Url: "/#tickets"
      Title: "Tickets"
    - Url: "/blog/"
      Title: "Blog"
    # - Url: "https://www.papercall.io/goconca"
    #   Title: "Call for Papers "
    #   Icon: "fa-scroll"
    #   Target: "_blank"
    - Url: "/speakers/"
      Title: "Speakers"
    # - Url: "/partners/"
    #   Title: "Partners"
    # - Url: "/#diversity-scholarship"
    # Title: "Diversity Scholarship"
    #   Title: "Diversity Scholarship"
    - Url: "/contact/"
      Title: "Contact"
    - Url: "/#mailinglist"
      Title: "Subscribe"
    - Url: "/location/"
      Title: "Location"
    - Url: "/code-of-conduct/"
      Title: "Code of Conduct"

  # List of Sponsors
  # Sponsors:
  #   - name: "Hugo"
  #     logo: "/img/hugo.png"
  #     url: "http://gohugo.io"

  # List of Partners
  # Partners:
  #   - name: "Hugo"
  #     logo: "/img/hugo.jpg"
  #     url: "https://gohugo.io"
  #   - name: "BrazilJS"
  #     logo: "/img/partner.png"
  #     url: "http://braziljs.org"

  # The entire schedule
  # Schedule:
  #   - name: "Check-in / Breakfast"
  #     time: "9h00"

  #   - name: "Linus Torvalds"
  #     photo: "/img/speaker.jpg"
  #     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #     company: "Linux Foundation"
  #     link:
  #       href: "http://twitter.com/linus"
  #       text: "@linus"
  #     presentation:
  #       title: "Digging into a Linux Kernel"
  #       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #       time: "10h00"

  #   - name: "Bill Gates"
  #     photo: "/img/speaker.jpg"
  #     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #     company: "Microsoft"
  #     link:
  #       href: "http://github.com/billy95"
  #       text: "@billy95"
  #     presentation:
  #       title: "Introducing Windows 12"
  #       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #       time: "11h00"

  #   - name: "Lunch"
  #     time: "12h00"

  #   - name: "Chuck Norris"
  #     photo: "/img/speaker.jpg"
  #     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #     company: "Delta Command"
  #     link:
  #       href: "http://twitter.com/littlechuck"
  #       text: "@littlechuck"
  #     presentation:
  #       title: "How to kill a elephant with one finger"
  #       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #       time: "13h00"

  #   - name: "Steve Jobs"
  #     photo: "/img/speaker.jpg"
  #     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #     company: "Apple, Inc."
  #     link:
  #       href: "http://github.com/stevie"
  #       text: "@stevie"
  #     presentation:
  #       title: "Presenting iPad"
  #       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #       time: "14h00"

  #   - name: "Coffee-break"
  #     time: "15h00"

  #   - name: "Mark Zuckerberg"
  #     photo: "/img/speaker.jpg"
  #     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #     company: "Facebook"
  #     link:
  #       href: "http://twitter.com/zuck"
  #       text: "@zuck"
  #     presentation:
  #       title: "Revealing Facebook Secrets"
  #       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #       time: "16h00"

  #   - name: "Steve Wozniak"
  #     photo: "/img/speaker.jpg"
  #     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #     company: "Apple, Inc."
  #     link:
  #       href: "http://twitter.com/woz"
  #       text: "@woz"
  #     presentation:
  #       title: "Why do I prefer Android over iPhone"
  #       description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #       time: "17h00"
